kind: pipeline
name: arch-bce-packages

steps:
- name: build
  image: archlinux/base
  pull: always
  volumes:
    - name: build-products
      path: /tmp/products
  commands:
    - echo -e "[mbp]\nServer = http://dl.t2linux.org/archlinux/\$repo/\$arch" >> /etc/pacman.conf
    - pacman --noconfirm -Syyu
    - pacman-key --init
    - pacman-key --populate archlinux
    - pacman-key --recv-keys 7F9B8FC29F78B339
    - pacman-key --lsign-key 7F9B8FC29F78B339
    - pacman --noconfirm --needed -S base-devel sudo linux-mbp linux-mbp-headers
    - useradd builduser -m
    - passwd -d builduser
    - echo "PKGEXT='.pkg.tar.zst'" | tee -a /etc/makepkg.conf
    - echo "COMPRESSZST=(zstd -c -T0 -20 --ultra -)" | tee -a /etc/makepkg.conf
    - printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers # passwordless sudo
    - chown -R builduser:builduser ./
    - sudo -u builduser bash -c 'makepkg -s --noconfirm'
    - ls -lah *.pkg.tar.xz
    - mv *.pkg.tar.xz /tmp/products
  when:
    event: tag

- name: sign
  image: plugins/gpgsign
  volumes:
    - name: build-products
      path: /tmp/products
  settings:
    key:
      from_secret: signing_key
    passphrase:
      from_secret: signing_key_password
    files:
      - /tmp/products/*
    armor: false
    detach_sign: true
  when:
    event: tag

- name: publish-github
  image: plugins/github-release
  volumes:
    - name: build-products
      path: /tmp/products
  settings:
    api_key:
      from_secret: github_token
    files: /tmp/products/*
    prerelease: yes
  when:
    event: tag

- name: publish-repo
  image: archlinux
  pull: always
  volumes:
    - name: build-products
      path: /tmp/products
    - name: temp-repo
      path: /tmp/repo
  environment:
    S3_ACCESS_ID:
      from_secret: s3_access_id
    S3_SECRET:
      from_secret: s3_secret
    S3_REGION:
      from_secret: s3_region
    S3_HOST:
      from_secret: s3_host
    S3_BUCKET_HOST:
      from_secret: s3_bucket_host
    S3_BUCKET:
      from_secret: s3_bucket
  commands:
    - pacman --noconfirm -Syyu
    - pacman --noconfirm --needed -S base s3cmd
    - s3cmd -s --region=$S3_REGION --host=$S3_HOST --host-bucket="$S3_BUCKET_HOST" --access_key=$S3_ACCESS_ID --secret_key=$S3_SECRET sync --follow-symlinks s3://$S3_BUCKET/archlinux/mbp/x86_64/ /tmp/repo/
    - mv /tmp/products/* /tmp/repo/
    - cd /tmp/repo/
    - repo-add -n -R -p $PWD/mbp.db.tar.gz *.pkg.tar.zst
    - s3cmd -s --region=$S3_REGION --host=$S3_HOST --host-bucket="$S3_BUCKET_HOST" --access_key=$S3_ACCESS_ID --secret_key=$S3_SECRET sync --follow-symlinks --delete-removed /tmp/repo/ s3://$S3_BUCKET/archlinux/mbp/x86_64/
  when:
    event: tag

volumes:
- name: build-products
  temp: {}
- name: temp-repo
  temp: {}
